### ISSUE TITLE
Keep yml file?

### ISSUE THREAD

**Issue by DEQrshojin** [PythonCodersOR/ordeqwdm#1]
Once the environment from the .yml file has been created, do I need to keep it. I am going to move the project to the E drive, and I would like to delete C:\Temp.

More generally, would you recommend the creation of project or task specific yml files or is it overkill in most instances?

**Comment by kbrannan** [comment]
I would make createion of the environment (yml file) a specific task in the workflow. It might not be a big deal if you are using packages that most people use. However, including the requirements for your module explicitly would reduce the headaches of future users if problems do occur.

**Comment by kbrannan** [comment]
The environment needs to be activated in Visual Studio 2017 for you to use the specific packages in your module. I am not going into what you would need to do to run your module outside of the IDE just yet. The environment could be located anywhere as long as you have access to it. If you use Anaconda to manage your environments, that software creates and managesthe environment in a specific place. I strondly recomend using Anaconda (more specifically the command line version 'miniConda' to create and manage your python environments.
