### ISSUE TITLE
Can't create the .uci with the .wdm input file

### ISSUE THREAD

**Issue by DEQrshojin** [PythonCodersOR/ordeqwdm#2]
Hi Kevin,

When you have a moment, could you help me out with another issue? I'm trying to construct the control file, however I'm getting an error related to the wdm input file. When using pyHSPF, it has it's own method for creating the input wdm, which necessarily modifies the hspfmodel instance to expect that wdm file. But because we created the wdm file outside of that method it doesn't like it and I can't find a way to point the hspfmodel instance to our wdm file. At least that's what I think is going on. Anyway, I've tried a few different things, including creating the wmd file with WMDUtil, but in all instances, I get no joy.

If what I just describe is nonsensical, I can explain better with a drawing.

Cheers,
Ryan

**Comment by kbrannan** [comment]
Post the uci and wdm files that you are having trouble with in this repo and I will download them and see what I can do

**Comment by DEQrshojin** [comment]
I've uploaded the wdm to the repo. I was unable to create the uci. Cheers

**Comment by kbrannan** [comment]
Great, I will take a look at the files. I have some Willamette Hg work I need to get out, so I may not get to this until later this week.

**Comment by DEQrshojin** [comment]
In working through this issue, I found that even though we specified the location of the message file at the beginning in the code, when pyHSPF creates the instance of the model, it sets a new message file path to where the environment is set (in User\AppData\Local\conda...). So I just reset the path prior to creating the wdm input It seems to work, but rewrites the wdm input, and modifies it. I'm not sure if those changes are what we want but I am looking into that.

Also, however I have another issue in creating the uci. It's almost to the end, but gets hung up on adding the Ftable blocks, so I'm trying to figure that out now. If you do have some time, let me know...

**Comment by kbrannan** [comment]
Please upload the files (wdm, uci, and  ...) you are using to run HSPF and I will take a look at the messages generated from the error.

**Comment by DEQrshojin** [comment]
The wdm file is in https://github.com/PythonCodersOR/ordeqwdm/tree/master/wdm_in. I am unable to create the uci.

**Comment by kbrannan** [comment]
Got it. Write a short python function that gets the dataset info from the wdm file you created and write that info to a text file.
Include the DNS number and the name for each data set in the wdm file.

Let's talk about creating a uci file.

**Comment by DEQrshojin** [comment]
I've uploaded the scripts to https://github.com/PythonCodersOR/ordeqwdm/tree/master/wdm_in.

The wdm_functions.py is what I used to create input the datasets into the wdm.

The DSNs for precip are 101-117 for each subbasin (1-17). The DSNs for PET are 201-217. The DSN for flow is 301.

I think I've gotten through the last hiccup for creating the uci file, but need to make sure. I'll let you know how it goes.

**Comment by DEQrshojin** [comment]
Was able to create the uci, I have put it in the wdm_in folder

**Comment by kbrannan** [comment]
Cool, does it HSPF run with the files?

**Comment by DEQrshojin** [comment]
Kinda--it processes fine but is unstable hydraulically. I'm gonna review the ftables to see if it's off a decimal place somewhere.

**Comment by kbrannan** [comment]
Ok
I am going to close this issue since you created the uci
