### ISSUE TITLE
FTABLE max detp

### ISSUE THREAD

**Issue by kbrannan** [PythonCodersOR/ordeqwdm#3]
I looked at the FTABLEs in the uci file you created. Ithink the problem could be that your max depth may not be large enough. HSPF will get unstable if it encouters flow depths in reaches that are greater than the max depth in the FTABLE for the reach. The way to address that is to set the max depth to a value that is not likely to occur. For the depth in the FTABLE at the link below, I would add another row for a depth much greater than 6.05, Something like 60 or greater.  Calculate the reast of the FTABLE vaules for the max depth using the some procedures you used to create the FTABLE.
https://github.com/PythonCodersOR/ordeqwdm/blob/1770210d17e6f5868cd7490ea90933ff10906517/wdm_in/siletz_river.uci#L3572

**Comment by DEQrshojin** [comment]
Yeah, that did the trick. Closing the issue...

**Comment by kbrannan** [comment]
great
